language: cpp
cache:
  apt: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - sourceline: 'ppa:allegro/5.2'
          packages:
            - g++-5
            - liballegro5-dev
            - liballegro-acodec5-dev
            - liballegro-audio5-dev
            - liballegro-dialog5-dev
            - liballegro-image5-dev
            - liballegro-ttf5-dev
            - liballegro-video5-dev
            - libboost1.55-all-dev
        artifacts:
          working_dir: travis-build
          debug: true
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - boost-latest
            - sourceline: 'ppa:allegro/5.2'
          packages:
            - clang-4.0
            - liballegro5-dev
            - liballegro-acodec5-dev
            - liballegro-audio5-dev
            - liballegro-dialog5-dev
            - liballegro-image5-dev
            - liballegro-ttf5-dev
            - liballegro-video5-dev
            - libboost1.55-all-dev
        artifacts:
          working_dir: travis-build
          debug: true
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
before_install:
  - eval "${MATRIX_EVAL}"
install: true

script: mkdir travis-build && cd travis-build && cmake -DWANT_TEST:BOOL=ON -DCMAKE_BUILD_TYPE=Release .. && make

env:
  global:
  - "ARTIFACTS_AWS_REGION=eu-west-1"
  - "ARTIFACTS_S3_BUCKET=cbe-build.vesalaakso.com"
  - secure: "c8GGiN8yUZZUQtG9vKvWU8KgobovraZ1Sqg7Y6uhKgPPQZOSoUTlFnWD1OcE0j7KcDuDX1l5uR2tlVrMWkviD7XRKf+AE3BykEyiPWMJfYLTDN0QHOcfG+464wsYIoz8rD7r8qgit0NABMh8jWAvuopCCS16rIvgnbO5DLUjsG4="
  - secure: "Q7YyA0hd5UoYUGg7EPvnLJtsT8+6J8NUiEgS5lqmk27JwoUS5HwjToLwWmv+xEGBzim2L2MceI1ZHEqBAPgD5z8mcQhBmVUOjkH/JuOKKouW4+/XDZuOTXaZbrrTFtGaZQ3Oi0KDPpcYp5GQfI5KwsFiCMRNT9jgWzXQ8cP4tPI="
