language: cpp
cache:
  apt: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - sourceline: 'ppa:allegro/5.2'
          packages:
            - g++-5
            - liballegro5-dev
            - liballegro-acodec5-dev
            - liballegro-audio5-dev
            - liballegro-dialog5-dev
            - liballegro-image5-dev
            - liballegro-ttf5-dev
            - liballegro-video5-dev
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - boost-latest
            - sourceline: 'ppa:allegro/5.2'
          packages:
            - clang-4.0
            - liballegro5-dev
            - liballegro-acodec5-dev
            - liballegro-audio5-dev
            - liballegro-dialog5-dev
            - liballegro-image5-dev
            - liballegro-ttf5-dev
            - liballegro-video5-dev
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
before_script:
  - "gem install travis-artifacts"
before_install:
  - eval "${MATRIX_EVAL}"
install: true

script: mkdir travis-build && cd travis-build && cmake -DWANT_TEST:BOOL=ON -DCMAKE_BUILD_TYPE=Release .. && make

after_test:
  - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"

env:
  global:
  - "ARTIFACTS_AWS_REGION=eu-central-1"
  - "ARTIFACTS_S3_BUCKET=cbe.vesalaakso.com"
  - secure: QNNvvzT4ldqd/4yTSSAKOoOmhoK9yHuWM98kfX4KvEjeejVP1CZojCMBXqklF1e9NTVV05ThdhzsEwkN9b1NUwt7JH5Vw+6+3O8Dg8Zpl9+cZemoDr+JX4AKVPoZbDLja9GKo1rYZmNDGbujqvw1ADvBA5n27bDVbmHAoiAPEdQ=
  - secure: IZyjE6yp4hQ9a4s6G+VbeeftNyKW7ISbqC9wB6goQARIRnQ3iLDBZG77Xdj9wrduWLdLe7dkX8EzGrhfRiANccyA1ImRDTRp+BoWegZylqs6bclgTitk00Kg2LqA5BJ4f4D9mS6KVrzwiuEvBvjkE9b50qIpEOsy88pHttGxZWA=
